### ISSUE TITLE
Using django.utils.importlib which is depricated in Django 1.9

### ISSUE THREAD

**Issue by pjcuadra** [hzdg/django-periodically#13]
I can get it to work with Django 1.9. The first issue I encountered was this one. According to https://docs.djangoproject.com/en/1.9/internals/deprecation/. The `django.utils.importlib` you are importing in `utils.py` is depricated.

**Comment by belgacea** [comment]
Modifying [utils.py](https://stackoverflow.com/questions/35348595/django-upgrade-from-1-7-1-to-1-9-2-importerror-cannot-import-name-importlib) file from :
`from django.utils import importlib, timezone`
to :
`from django.utils import timezone`
`import importlib`
throws an AppRegistryNotReady exception when trying to runserver or migrate.

Full trace :

> Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001A1E3F67840>
> Traceback (most recent call last):
>   File "virtualenv_dir\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
>     fn(_args, *_kwargs)
>   File "virtualenv_dir\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
>     autoreload.raise_last_exception()
>   File "virtualenv_dir\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
>     six.reraise(__exception)
>   File "virtualenv_dir\lib\site-packages\django\utils\six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "virtualenv_dir\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
>     fn(_args, **kwargs)
>   File "virtualenv_dir\lib\site-packages\django__init__.py", line 18, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "virtualenv_dir\lib\site-packages\django\apps\registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "virtualenv_dir\lib\site-packages\django\apps\config.py", line 90, in create
>     module = import_module(entry)
>   File "virtualenv_dir\lib\importlib__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
>   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>   File "virtualenv_dir\lib\site-packages\periodically__init__.py", line 3, in <module>
>     from .utils import get_scheduler_backend_class
>   File "virtualenv_dir\lib\site-packages\periodically\utils.py", line 4, in <module>
>     from .models import ExecutionRecord
>   File "virtualenv_dir\lib\site-packages\periodically\models.py", line 14, in <module>
>     class ExecutionRecord(models.Model):
>   File "virtualenv_dir\lib\site-packages\django\db\models\base.py", line 94, in **new**
>     app_config = apps.get_containing_app_config(module)
>   File "virtualenv_dir\lib\site-packages\django\apps\registry.py", line 239, in get_containing_app_config
>     self.check_apps_ready()
>   File "virtualenv_dir\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
>     raise AppRegistryNotReady("Apps aren't loaded yet.")
> django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by kolsiA** [comment]
@belgacea 
on utils.py, you need to declare the "from .models import ExecutionRecord" inside  "get_scheduled_time"

**Comment by jgtvares** [comment]
@kolsiA 
Doing that raises `ModuleNotFoundError: No module named 'django.utils.importlib'`
And I'm not even importing **importlib** from **django.utils**, just `import importlib`
